### ISSUE TITLE
Pawn cannot turn into a queen

### ISSUE THREAD

**Issue by juaorteg** [pioz/chess#10]
Hello,

I ran into an issue while playing.
The Chess::IllegalMoveError is raised when the pawn tries to go to the end of the board and become a queen.

**Comment by juaorteg** [comment]
Sorry, I wasn't aware the rook can become a queen/knight/rook/bishop.
Adding a "Q" after the move works.
The default is usually queen in chess games.

**Comment by pioz** [comment]
Ok, I can add this feature in the next days... thank you for your suggestion...

**Comment by pioz** [comment]
If no promotion char is passed use 'q' as default in version 0.0.9
