### ISSUE TITLE
Could use move generation

### ISSUE THREAD

**Issue by dkappe** [pioz/chess#13]
For a chess library, it seems the absence of legal move generation is an is an oversight. Hopefully it would be easy to add. It's the only thing keeping this library from being truly useful.

**Comment by pioz** [comment]
There is a draft: http://blog.pioz.it/chess/classes/Chess/Gnuchess.html

**Comment by dkappe** [comment]
I meant legal love generation, I.e. A list of all legal moves, not the best move selected by an engine.

DJK

**Comment by pioz** [comment]
Ok, I will work on this, but I dont know when -.-

**Comment by dkappe** [comment]
I can give it a whack, but a hint on how to do it most efficiently would be
appreciated.

DJK

**Comment by pioz** [comment]
I think that a efficiently way is to use the xray bitboard. For example I want to know all the possible valid move that `Qd1` can make: I can get the xray bboard with `xray (cur_board, 3, FALSE)`. Now you can use the method `try_move` for every pseudo legal move indicated by the xray bboard.

**Comment by pioz** [comment]
Now you can generate all legal moves for the piece in a square position:

    :001 > g = Chess::Game.new
     => #<Chess::Game:0x007f88a529fa88>
    :002 > g.board.generate_moves('b1')
     => ["Na3", "Nc3"]
