### ISSUE TITLE
Algebraic input

### ISSUE THREAD

**Issue by dsaito** [pioz/chess#14]
Dear Pioz, does Chess gem have a method that allows the user to enter a move in algebraic format (e.g. Nxf6) and get the ouput in coordinate format (G8F6)? By the way, this gem is great.

**Comment by pioz** [comment]
Currently no, but I can work on this in the next few days.

**Comment by dsaito** [comment]
Ok, man, that would be truly great. I'm currently trying to develop a simple chess interface that uses book moves in pgn format (which are written in algebraic format) along with Stockfish. I'll wait for the changes, thank you.

**Comment by pioz** [comment]
You can get the array with all moves done in coordinate chess notation with `g.coord_moves`. To get the last move done in coordinate chess notation format use `g.coord_moves.last`. Let me know if this can close this issue please.

**Comment by dsaito** [comment]
Thank you so much, Enrico! This will help A LOT and close the issue. Best regards from Brazil.
Daniel
