### ISSUE TITLE
Taking back a move

### ISSUE THREAD

**Issue by dsaito** [pioz/chess#15]
Dear Enrico, how can I take back a move?

**Comment by pioz** [comment]
You can use `rollback!`

http://pioz.github.com/chess/classes/Chess/CGame.html#method-i-rollback-21

**Comment by dsaito** [comment]
I tried the rollback! method, but it clears all moves from moves and coord_moves. That means it is taking back all moves. I don't know what I'm doing wrong here...

**Comment by pioz** [comment]
Can you show me the code?

**Comment by dsaito** [comment]
I feel silly now. I had reset the game object (g = Chess::Game.new) prior to applying the rollback! method. I simply forgot to remove this line of code from my previous script editing. That explains the clearing of the move array.
