### ISSUE TITLE
Load PGN string instead of file?

### ISSUE THREAD

**Issue by raquelhortab** [pioz/chess#18]
Hi there! 

I was wondering if there is a way to load the pgn to create the game in string format instead of having to create a file.

Thanks!

**Comment by pioz** [comment]
At this time is not possible. I can add this feature on the weekend!

**Comment by raquelhortab** [comment]
That would be amazing! 

For instance, I am using chessboard.js with chess.js, and I was intending to check in the server whether the moves were legal with chess gem before saving the state of the game.

[PGN]((https://en.wikipedia.org/wiki/Portable_Game_Notation) in chess.js is in the standard format: strings like "1. d3 e6 2. d4 e5 3. dxe5 g6". It would be interesting that pgn.rb load and to_s functions followed the standard format.

Thanks for the amazing and quick support!

**Comment by pioz** [comment]
I've just added this new method to the class `Chess::Pgn` http://blog.pioz.it/chess/Chess/Pgn.html#load_from_string-instance_method and a couple of tests. Here the [commit](https://github.com/pioz/chess/commit/de7817aba350e3b874499837115bcf69c766d937).

**Comment by pioz** [comment]
Let me know if this can resolve your problem!

**Comment by raquelhortab** [comment]
Hi! Well, I'm having problems with the version issue. I am trying to unpack the gem, modify it to be able to use it with ruby 1.9 and rebuild it. However, when I try to do `gem build` I get an error:

```
gem build chess.gemspec 
Invalid gemspec in [chess.gemspec]: undefined local variable or method `__dir__' for Gem::Specification:Class
ERROR:  Error loading gemspec. Aborting.
```

**Comment by raquelhortab** [comment]
Hi there!
Well... actually it does not... I need to use it with ruby 1.9 and I cannot find the workaround, I've been trying to unpack, modify, and rebuild the gem but since I am a noob in this, I cannot get it to work...

**Comment by raquelhortab** [comment]
Thank you very much for your help though!! Magnificient support!!!

**Comment by pioz** [comment]
@raquelhortab, unfortunately, Ruby 1.9 is no more supported by this gem.
