### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by raquelhortab** [pioz/chess#19]
Hi!
In the description says Ruby 1.9 or higher is needed. However, I am using 1.9 and it does not work. In fact some notation used in the code seems to be for Ruby 2.x:

```
Uncaught exception: /home/raquel/.rvm/gems/ruby-1.9.3-p551@codelearn/gems/chess-0.2.2/lib/chess/pgn.rb:42: syntax error, unexpected tLABEL
    def initialize(filename = nil, check_moves: false)
```

Any workaround or version that actually works with Ruby 1.9?

**Comment by raquelhortab** [comment]
By modifying a couple of lines that use this notation seems to work (at least the application runs)

**Comment by pioz** [comment]
You're right. Now the gem uses the Ruby 2+ keyword arguments syntax. We need to update the README and docs. So the gem requires Ruby 2+.

**Comment by raquelhortab** [comment]
actually if you change (in pgn.rb) 

 `def load(filename, check_moves:  false)`  to  `def load(filename, check_moves= false)`

and

`def initialize(filename = nil, check_moves: false)` to `def initialize(filename = nil, check_moves= false)`

it seems to work just fine with ruby 1.9 :)
