### ISSUE TITLE
PGN is not in a standard format

### ISSUE THREAD

**Issue by raquelhortab** [pioz/chess#20]
Hi, sorry for opening so many issues but this is the most downloaded chess gem and I do not understand how there are so many things that seem irregular.

PGN is supposed to be a string that looks something like:

1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 {This opening is called the Ruy Lopez.}
4. Ba4 Nf6 5. O-O Be7 6. Re1 b5 7. Bb3 d6 8. c3 O-O 9. h3 Nb8 10. d4 Nbd7
11. c4 c6 12. cxb5 axb5 13. Nc3 Bb7 14. Bg5 b4 15. Nb1 h6 16. Bh4 c5 17. dxe5
Nxe4 18. Bxe7 Qxe7 19. exd6 Qf6 20. Nbd2 Nxd6 21. Nc4 Nxc4 22. Bxc4 Nb6
23. Ne5 Rae8 24. Bxf7+ Rxf7 25. Nxf7 Rxe1+ 26. Qxe1 Kxf7 27. Qe3 Qg5 28. Qxg5
hxg5 29. b3 Ke6 30. a3 Kd6 31. axb4 cxb4 32. Ra5 Nd5 33. f3 Bc8 34. Kf2 Bf5
35. Ra7 g6 36. Ra6+ Kc5 37. Ke1 Nf4 38. g3 Nxh3 39. Kd2 Kb5 40. Rd6 Kc5 41. Ra6
Nf2 42. g4 Bd3 43. Re6 1/2-1/2

However, this gem seems to use a custom format (not real PGN) making it incompatible with other tools (chess.js for instance) 

I am wrong or is there a way to get the correct PGN string out of a PGN object?

**Comment by pioz** [comment]
Thank you to open so many issues!
Can you attach here a PGN format that does not work?

**Comment by raquelhortab** [comment]
Well I tried writing to a file a PGN string (for instance: "1. d3 e6 2. d4 e5 3. dxe5 g6") and it does not accept the format. I see that the funciton pgn.to_s does not provide this format either but some kind of string representation of your pgn ruby object (variables and all), which I guess is what the load_pgn function expects to find in the file.

PS: Thanks for answering so fast!!

**Comment by raquelhortab** [comment]
Okey I see now, maybe it was my fault, sorry! The .to_s function works just fine. My problem could be that I was not writing the headers in the file. I will test it more but with the string load functionality from the other issue, it might be enough.

I will close this as it seems it was my mistake :)

Thanks!
