### ISSUE TITLE
Segmentation fault in move generator

### ISSUE THREAD

**Issue by kamil98** [pioz/chess#23]
Generating possible moves for this position: `rnbqkbnr/1ppppppp/8/8/pP2P3/P7/2PP1PPP/RNBQKBNR w KQkq - 0 3'` and the C2 field leads to a segmentation fault.

I added a failing spec here: https://github.com/kamil98/chess/commit/a452c9f88b7ffea90978a11674313e00bfb9f59e

I tested it with ruby 2.7.2.

**Comment by pioz** [comment]
I've added your spec (https://github.com/pioz/chess/commit/f8056dc34203897ebf616a25223726494fa91ea8) and then I' ve  tried to run the test on my machine with ruby 2.7.2:
```
cd ext
ruby extconf.rb
make
cd ..
rake test
```
I get no errors and all test passed.

Can you provide more info?

**Comment by kamil98** [comment]
Sadly I can't reproduce it now, even with the same spec :(

I saved the crash report, hope it helps.

[ruby_2021-01-17-224509_MacBook-Pro-Kamil.crash.txt](https://github.com/pioz/chess/files/5860652/ruby_2021-01-17-224509_MacBook-Pro-Kamil.crash.txt)

**Comment by kamil98** [comment]
Since the bug is not reproducible I guess I'll just close the issue.

Thanks for your help!
