### ISSUE TITLE
Documentation link in README doesn't work

### ISSUE THREAD

**Issue by timburgan** [pioz/chess#25]
Hello @pioz 

The documentation link in the README https://github.com/pioz/chess/blob/master/README.md?plain=1#L37 is returning a 404.

```
**Documentation** is available **[here](http://pioz.github.com/chess)**.
```

Is there a bug in the GitHub Pages generation of the documentation?

Thanks,
Tim

**Comment by pioz** [comment]
Thank you for your issue. The link is broken because GitHub pages do not work anymore under the domain github.com but only github.io.

[Fixed](https://github.com/pioz/chess/commit/d307ee036a6258d987e54617dd4bf679cb6dd73c).
