### ISSUE TITLE
Unexpected behavoir moving a piece

### ISSUE THREAD

**Issue by justbyitself** [pioz/chess#31]
I've found an unexpected beahvoir in pioz/chess. 
When my board is like this:
```
8 . . . . Q . . . 
7 . . . . . . . . 
6 . . . . . . . . 
5 . . . . . . . . 
4 . . . . . . . . 
3 . . . . . . . . 
2 . . . . K . . . 
1 . . . . . . . k 
  a b c d e f g h
```
and I try `game << 'e8a8'`, I get this board:
```
8 . . Q . . . . . 
7 . . . . . . . . 
6 . . . . . . . . 
5 . . . . . . . . 
4 . . . . . . . . 
3 . . . . . . . . 
2 . . . . K . . . 
1 . . . . . . . k 
  a b c d e f g h
```
Piece (Q) moved from e8 to c8, instead a8, why?
Note: No exception raises

A gist in order to reproduce this issue: https://gist.github.com/justbyitself/e4d4615a17181526f0359f3437221053

Thank you for your library.

**Comment by pioz** [comment]
Ok, I'll check in the next few days! Thanks for the issue.

**Comment by pioz** [comment]
I've fix the problem [here](https://github.com/pioz/chess/commit/15b5078c0ce01bf53e69a631a860464b2b7298c1). You can install the new release v0.3.5.

Please, let me know if the issue is fixed. Thanks.

**Comment by justbyitself** [comment]
OK. Fixed! Thanks.
