### ISSUE TITLE
Generate all (legal) moves

### ISSUE THREAD

**Issue by justbyitself** [pioz/chess#33]
You can generate all legal moves from an specific square, for example:
`game.board.generate_moves('e2')`

But you don't have a method in order to generate **all** legal moves (from any square). Of course you can calculate it using `generate_moves` method (see https://gist.github.com/justbyitself/4ab2265358dcdafffcc37d45f686a8d4 as example) but it would be nice if this library would do that work for you.

Another chess libraries (coded in other languages) have this feature, for example:
* https://python-chess.readthedocs.io/en/latest/core.html#chess.Board.legal_moves
* https://github.com/jhlywa/chess.js?tab=readme-ov-file#moves-piece-piece-square-square-verbose--false--

Thank you again.

**Comment by pioz** [comment]
I have add the new method [`board.generate_all_moves`](https://pioz.github.io/chess/Chess/Board.html#generate_all_moves-instance_method).

You can start using this method from v0.4.0.

**Comment by justbyitself** [comment]
Thank you!
