### ISSUE TITLE
Memory issue on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by alexggordon** [pioz/chess#8]
Hey, 

So I've been running into a reproducible issue on Ubuntu 14.04.1, with Ruby 2.1.0 through 2.2.0 (haven't tested before ruby 2.1.0) where every time I try and use the set_fen method, ruby crashes with a ``` Error in `irb': free(): invalid next size (fast): 0x00007f2f89f17ae0 ``` (obviously the memory location changes every time). I've been working around this in the mean time by modifying the [pgn class](https://github.com/alexggordon/chess/blob/master/lib/chess/pgn.rb) to accept strings while I try and figure out the issue, however, I'm running out of ideas, and since you wrote the C library backing the gem I was wondering if you had any thoughts on it? 

I'm currently working on setting up a docker container to reproduce the error for you, but I figured I'd start the discussion now. 

Thanks!

**Comment by pioz** [comment]
Ok, I'll wait your docker container... I cant reproduce this error with my enviroments.

**Comment by alexggordon** [comment]
Created and pushed a [docker](https://registry.hub.docker.com/u/alexggordon/chess/) repository with Ubuntu 14.04 and Ruby 2.2.0/2.1.5 through rbenv. 

Steps to reproduce: 
```bash
root@d04ee708e681:~# irb
irb(main):001:0> require 'chess'
=> true
irb(main):002:0> g = Chess::Game.load_fen('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')
*** Error in `irb': free(): invalid next size (fast): 0x00007f43132f2350 ***
Aborted
```

Any ideas? I was playing around with seeing if I could boot the gem in valgrind or something, but I haven't used mkmf much at all.

**Comment by pioz** [comment]
Ok, I've pushed some changes, can you check if now works? You can use the master branch.

**Comment by alexggordon** [comment]
Awesome. Looks good! Seems to work perfectly. Would you mind deploying the ruby gem too? Thanks!

**Comment by pioz** [comment]
(y) pushed!
